#pragma once

#define APP_VERSION_MAJOR 4
#define APP_VERSION_MINOR 7
#define APP_VERSION_PATCH 1

#define APP_BUILD_MAJOR 1
#define APP_BUILD_MINOR 1
#define APP_BUILD_PATCH 2
#define APP_BUILD_NUMBER 112  // integer for auto-update comparison

#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

#define APP_BUILD_STRING STR(APP_BUILD_MAJOR) "." STR(APP_BUILD_MINOR) "." STR(APP_BUILD_PATCH)
#define APP_VERSION_STRING "v" STR(APP_VERSION_MAJOR) "." STR(APP_VERSION_MINOR) "." STR(APP_VERSION_PATCH) " (Build " APP_BUILD_STRING ") Stable"
